### PR TITLE
ethernet: fix Q-in-Q implementation, add Frame.ServiceVLAN

### LINKED ISSUE #2: ethernet: issue with Q-in-Q tagging
It appears I've made a mistake with my Q-in-Q tagging implementation.

https://en.wikipedia.org/wiki/IEEE_802.1Q#Double_tagging

Note that the TPID for S-VLAN is different than C-VLAN.  I'll probably just end up splitting them into two separate fields instead of the slice that exists now.

### PR DESCRIPTION
**Pull request by mdlayher**
Fixes #2 .

### CODE REVIEW

File: ethernet.go [hunk 1]
```diff
@@ -236,10 +258,67 @@ func (f *Frame) length() int {
...
+		vlan := new(VLAN)
+		if err := vlan.UnmarshalBinary(b[n : n+2]); err != nil {
+			return 0, err
+		}
+
+		f.VLAN = vlan
+		f.EtherType = EtherType(binary.BigEndian.Uint16(b[n+2 : n+4]))
+		n += 4
+	default:
+		panic(fmt.Sprintf("unknown VLAN TPID: %04x", tpid))
```
Comment (bradleyfalzon) [inline ethernet.go]: Why not return the error here?

Comment (mdlayher) [inline ethernet.go]: Since this method should only be called when either of the two listed EtherType values are present, I added this as a fail-safe to indicate an obvious bug.  I had thought about an error return, but a panic seemed more clear to signal that an EtherType value was handled incorrectly.
